security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

    providers:
        user:
            entity:
                class: 'App\Entity\User' 
                property: 'api_token'
    
    firewalls:
       
        main:
            pattern: ^/articles
            
            guard:
                authenticators:
                    - 'TokenAuthenticator'

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
