controllers:
    resource: ../../src/Controller/
    type: annotation

Article:
    type:     rest
    host: '%host%'

    resource: App\Controller\ArticleController


User:
    type:     rest
    host: '%host%'
    resource: App\Controller\UserController



api_login_check:
    path: /api/login_check


