controllers:
    resource: ../../src/Controller/
    type: annotation

Article:
    type:     rest
    host:     localhost
    resource: App\Controller\ArticleController


User:
    type:     rest
    host:     localhost
    resource: App\Controller\UserController


